/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: UselessViking (https://sketchfab.com/UselessViking)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/dark-souls-bonfire-b0d68c8f4cd0487da3d1fb8327ab1044
title: Dark Souls - Bonfire
*/

import React, { useEffect, useContext } from "react";
import { useGLTF } from "@react-three/drei";
import { useLoad } from "../Context/isLoaded";

export function Bonfire(props) {
  const { setLoaded } = useLoad();
  useEffect(() => {
    setLoaded(true);
  }, []);
  const { nodes, materials } = useGLTF("/Assets/BonfireModel/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.defaultMaterial.geometry}
            material={materials.schaedel}
          />
          <mesh
            geometry={nodes.defaultMaterial_1.geometry}
            material={materials.knochen}
          />
          <mesh
            geometry={nodes.defaultMaterial_2.geometry}
            material={materials.griff}
          />
          <mesh
            geometry={nodes.defaultMaterial_3.geometry}
            material={materials.steine}
          />
          <mesh
            geometry={nodes.defaultMaterial_4.geometry}
            material={materials.boden}
          />
          <mesh
            geometry={nodes.defaultMaterial_5.geometry}
            material={materials.klinge}
          />
          <mesh
            geometry={nodes.defaultMaterial_6.geometry}
            material={materials.asche}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/Assets/scene.gltf");
