/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: lumoize (https://sketchfab.com/lumoize)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/old-stone-tile-with-displacement-d2ab8669d0d346eda44fa35d793bdc81
title: Old Stone Tile (With Displacement)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Floor(props) {
  const { nodes, materials } = useGLTF("/Assets/FloorModel/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <group
        rotation={[-Math.PI / 2, 0, 0]}
        scale={20.23}
        position={[0, -0.55, 0]}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.pPlane1_lambert1_0.geometry}
            material={materials.lambert1}
          />
          <mesh
            geometry={nodes.pPlane1_lambert1_0_1.geometry}
            material={materials.lambert1}
          />
          <mesh
            geometry={nodes.pPlane1_lambert1_0_2.geometry}
            material={materials.lambert1}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/Assets/FloorModel/scene.gltf");
